angular.module("weekworkApp").controller("fon2",function($scope,$http){
	$http({
		url:"http://www.somenote.cn:1602/list1",
		method:"GET"
	}).success(function(e){
		$scope.data=e
	})
	$http({
		url:"http://www.somenote.cn:1602/list2",
		method:"GET"
	}).success(function(e){
		$scope.data1=e
	})
})